export const cmsGroups = [
  { title: "Homepage", ids: ["site_settings", "hero_banners", "homepage_features", "services", "applications", "operational_domains", "impact_stats", "quick_links", "geoportals"] },
  { title: "Pages", ids: ["about_pages", "division_pages", "facility_pages", "academic_pages", "pages"] },
  { title: "Navigation and appearance", ids: ["page_sections", "page_display_settings", "design_settings", "menu_items", "contact", "logos"] },
  { title: "Divisions", ids: ["divisions", "projects", "publications"] },
  {
    title: "People and Our Formers",
    ids: [
      "people_page_text",
      "our_formers_pages",
      "people_former_scientists",
      "scientific_manpower_page",
      "people_scientists",
      "people_leadership",
      "people_officials",
      "people_technical_staff",
      "people_administration",
      "manpower",
      "organisation_roles",
    ],
  },
  {
    title: "Public information",
    ids: [
      "rti_page",
      "appellate_authority_page",
      "memorandum_page",
      "general_service_rules_page",
      "feedback_page",
      "tenders",
      "faq",
      "policies",
      "notices",
      "flood_page_settings",
      "flood_reports",
      "gallery",
      "mobile_apps",
    ],
  },
];
