const text = (name, label, options = {}) => ({ name, label, type: "text", localized: true, ...options });
const textarea = (name, label, options = {}) => ({ name, label, type: "textarea", localized: true, ...options });
const plain = (name, label, options = {}) => ({ name, label, type: "text", localized: false, ...options });

const divisionOptions = [
  ["agriculture-resources-division1", "Agriculture Resources Division"],
  ["computer-image-processing-division", "Computer Image Processing & Data Management"],
  ["earth-resources-division1", "Earth Resources Division"],
  ["forest-resources-ecology-division", "Forest Resources and Ecology Division"],
  ["groundwater-resources-division1", "Groundwater Resources Division"],
  ["geo-spatial-data-bank-division1", "Geo-Spatial Data Bank Division"],
  ["landuse-amp;-urban-survey-division1", "Landuse and Urban Survey Division"],
  ["soil-resources-division1", "Soil Resources Division"],
  ["surface-water-resources-division1", "Surface Water Resources Division"],
  ["training-division", "Training Division"],
  ["school-of-geo-informatics-division1", "School of Geo-Informatics"],
].map(([value, label]) => ({ value, label }));

const divisionSectionOptions = [
  ["ongoing-projects", "Ongoing Projects"],
  ["completed-projects", "Completed Projects"],
  ["research-papers", "Research Papers / List of Research Papers"],
  ["technical-reports", "Technical Reports"],
  ["publications", "Publications"],
  ["training-programmes", "Training Programmes"],
  ["training-hostel", "Training Hostel"],
  ["overview", "Division Overview / Other List"],
].map(([value, label]) => ({ value, label }));

export const blockTypes = [
  { value: "hero", label: "Hero banner", description: "A large opening section with a heading, short text, image, and optional actions." },
  { value: "rich_text", label: "Text / paragraph", description: "Formatted paragraphs, headings, lists, links, and quotations." },
  { value: "cards", label: "Responsive cards", description: "A responsive group of repeated cards with titles, text, images, and links." },
  { value: "image", label: "Image", description: "One image with accessible alternative text and an optional caption." },
  { value: "gallery", label: "Gallery", description: "A responsive collection of images with alternative text and captions." },
  { value: "stats", label: "Statistics", description: "A row or grid of important numbers with short labels." },
  { value: "links", label: "Links / downloads", description: "A list of downloadable local files or clearly labelled web links." },
  { value: "table", label: "Table", description: "Column headings and rows for structured information." },
  { value: "callout", label: "Notice / callout", description: "A highlighted note or important short message." },
  { value: "divider", label: "Divider line", description: "A visual separator between sections; it contains no text." },
];

export const cmsIconOptions = [
  ["activity", "Activity / programme"],
  ["accessibility", "Accessibility"],
  ["arrow-right", "Right arrow"],
  ["arrow-up-right", "External-link arrow"],
  ["bed-double", "Hostel / accommodation"],
  ["bird", "Wildlife / ecology"],
  ["book-open", "Library / publication"],
  ["building", "Institution / office"],
  ["building2", "Building / facility"],
  ["clipboard", "Checklist / objectives"],
  ["compass", "Compass / explore"],
  ["cpu", "Computer / processing"],
  ["database", "Database / data bank"],
  ["document", "Document"],
  ["droplets", "Water resources"],
  ["education", "Education / training"],
  ["facebook", "Facebook"],
  ["file-text", "File / report"],
  ["flask-conical", "Laboratory"],
  ["flood", "Flood / surface water"],
  ["globe", "Globe / geoportal"],
  ["graduation-cap", "Graduation / academics"],
  ["help", "Help / FAQ"],
  ["home", "Home"],
  ["images", "Photo gallery"],
  ["landmark", "Government / institution"],
  ["layers", "Layers / spatial data"],
  ["map", "Map / location"],
  ["mountain", "Earth resources"],
  ["network", "Network / infrastructure"],
  ["notices", "Notices / announcements"],
  ["orbit", "Orbit / remote sensing"],
  ["phone", "Phone / mobile app"],
  ["printer", "Printing"],
  ["radar", "Radar / monitoring"],
  ["radio", "Radio / signal"],
  ["route", "Route / corridor"],
  ["ruler", "Measurement / survey"],
  ["satellite", "Satellite / remote sensing"],
  ["scan", "Scanning / image processing"],
  ["scan-line", "LiDAR / line scanning"],
  ["search", "Search"],
  ["shield", "Security / administration"],
  ["sprout", "Agriculture"],
  ["trees", "Forest resources"],
  ["twitter", "X / Twitter"],
  ["user-round", "Person / profile"],
  ["waves", "Surface water"],
  ["wrench", "Workshop / service"],
].map(([value, label]) => ({ value, label }));

export const cmsButtonLabelSuggestions = [
  { en: "Open", hi: "खोलें" },
  { en: "Open Portal", hi: "पोर्टल खोलें" },
  { en: "View details", hi: "विवरण देखें" },
  { en: "Read more", hi: "और पढ़ें" },
  { en: "View all", hi: "सभी देखें" },
  { en: "Download", hi: "डाउनलोड करें" },
  { en: "Visit website", hi: "वेबसाइट देखें" },
  { en: "Get directions", hi: "दिशा-निर्देश प्राप्त करें" },
  { en: "Back", hi: "वापस" },
];

export const pageCardIconOptions = [
  ["bed-double", "Hostel / accommodation"],
  ["book-open", "Library / publication"],
  ["building", "Building / facility"],
  ["sprout", "Agriculture"],
  ["cpu", "Computer / processing"],
  ["mountain", "Earth resources"],
  ["trees", "Forest resources"],
  ["droplets", "Groundwater"],
  ["database", "Data bank"],
  ["map", "Map / land use"],
  ["waves", "Surface water"],
  ["graduation-cap", "Training / academics"],
  ["landmark", "Institution"],
  ["user-round", "People"],
  ["satellite", "Remote sensing"],
  ["flask-conical", "Laboratory"],
  ["printer", "Printing"],
  ["scan-line", "Scanning / LiDAR"],
  ["wrench", "Workshop / service"],
  ["file-text", "Document"],
].map(([value, label]) => ({ value, label }));

export const collections = [
  {
    id: "pages",
    label: "Other Website Pages",
    description: "Policy, service, programme and public-information pages without another dedicated editor.",
    fields: [
      text("title", "Page title", { required: true }),
      plain("slug", "URL slug", { required: true, advanced: true }),
      plain("sectionKey", "Section key", { required: true, advanced: true }),
      text("eyebrow", "Eyebrow"),
      textarea("summary", "Summary"),
      { name: "html", label: "Legacy imported page content", type: "richtext", localized: true, advanced: true },
      { name: "blocks", label: "Flexible page blocks", type: "blocks", localized: true },
      { name: "featuredImage", label: "Featured image", type: "media", localized: false },
      { name: "headingSize", label: "Page heading size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }] },
      { name: "contentSize", label: "Body text size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }] },
      { name: "contentWidth", label: "Content width", type: "select", localized: false, options: [{ value: "compact", label: "Narrow" }, { value: "normal", label: "Normal" }, { value: "wide", label: "Wide" }, { value: "full", label: "Full width" }] },
      { name: "mediaSize", label: "Content image size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }, { value: "full", label: "Full width" }] },
      { name: "contentSpacing", label: "Content spacing", type: "select", localized: false, options: [{ value: "compact", label: "Compact" }, { value: "normal", label: "Normal" }, { value: "relaxed", label: "Relaxed" }] },
      { name: "hiddenProfileNames", label: "Hide profile cards by name", type: "list", localized: false, advanced: true },
      plain("sourceUrl", "Source URL", { type: "url", advanced: true }),
      { name: "cardIcon", label: "Index card icon", type: "select", localized: false, options: pageCardIconOptions },
      { name: "cardColor", label: "Index card primary colour", type: "color", localized: false },
      { name: "cardColor2", label: "Index card secondary colour", type: "color", localized: false },
    ],
  },
  {
    id: "page_sections",
    label: "Page Groups",
    description: "Top-level route groups and section introductions.",
    fields: [text("title", "Title"), plain("key", "Key", { required: true }), plain("route", "Route"), text("eyebrow", "Eyebrow"), textarea("intro", "Introduction")],
  },
  {
    id: "divisions",
    label: "Divisions",
    description: "Division cards and summaries.",
    fields: [text("title", "Division name", { required: true }), plain("slug", "Slug", { required: true }), textarea("lead", "Lead"), { name: "highlights", label: "Highlights", type: "list", localized: true }, plain("sourceUrl", "Source URL", { type: "url" })],
  },
  {
    id: "division_section_items",
    label: "Division List Items",
    description: "Add research papers, completed or ongoing projects, reports, publications and other division list records using a simple form.",
    autoNewestFirst: true,
    requireHindiWhenPublished: true,
    fields: [
      { name: "divisionSlug", label: "Division", type: "select", localized: false, required: true, allowCustom: true, options: divisionOptions },
      { name: "sectionKey", label: "Website section", type: "select", localized: false, required: true, options: divisionSectionOptions },
      text("title", "Item title", { required: true }),
      text("authors", "Authors / responsible officers"),
      text("publicationName", "Journal / department / publisher"),
      textarea("details", "Description / citation / project details"),
      plain("year", "Year", { type: "number" }),
      plain("date", "Date", { type: "date" }),
      { name: "documentUrl", label: "Upload document / file", type: "media", localized: false },
      plain("externalUrl", "External webpage URL", { type: "url" }),
    ],
  },
  {
    id: "facilities",
    label: "Facility Ordering Data",
    description: "Internal facility-card ordering data. Editors normally use the Facilities page collection.",
    fields: [text("title", "Facility name", { required: true }), plain("slug", "Slug"), textarea("text", "Description")],
  },
  {
    id: "profiles",
    label: "Scientists / Officials / Staff",
    description: "Scientists, leadership, officials, former staff, technical staff and administration.",
    fields: [
      text("name", "Name", { required: true }),
      { name: "profileType", label: "Profile type", type: "select", localized: false, options: ["scientist", "official", "leadership", "former", "technical", "administration"] },
      text("role", "Role"), text("designation", "Designation"), textarea("qualification", "Educational qualification"), text("department", "Department"), text("deployment", "Deployment"), plain("employeeId", "Employee ID"), text("duration", "Duration"),
      { name: "photo", label: "Photo", type: "media", localized: false }, plain("objectPosition", "Photo position"), textarea("specialization", "Specialization"), text("experience", "Experience"), text("publications", "Publications"), plain("contact", "Contact"), plain("email", "Email", { type: "email" }), plain("sourceUrl", "Source URL", { type: "url" }), text("category", "Category"), { name: "details", label: "Details", type: "list", localized: true },
    ],
  },
  {
    id: "projects",
    label: "Projects",
    description: "Completed and ongoing projects.",
    fields: [text("title", "Project title", { required: true }), { name: "type", label: "Project type", type: "select", localized: false, options: ["ongoing", "completed"] }, plain("divisionSlug", "Division slug"), plain("year", "Year"), text("client", "Client"), textarea("summary", "Summary"), { name: "url", label: "Upload project document / file", type: "media", localized: false }],
  },
  {
    id: "publications",
    label: "Publications / Research / Reports",
    description: "Research papers, technical reports, atlases and plans.",
    fields: [text("title", "Title", { required: true }), { name: "type", label: "Type", type: "select", localized: false, options: ["publication", "research_paper", "technical_report", "atlas", "plan"] }, plain("divisionSlug", "Division slug"), plain("year", "Year"), textarea("authors", "Authors"), textarea("citation", "Citation"), textarea("summary", "Summary"), { name: "url", label: "Upload document / file", type: "media", localized: false }],
  },
  {
    id: "notices",
    label: "Notices",
    description: "Public notices and documents.",
    fields: [text("title", "Notice title", { required: true }), text("category", "Category"), textarea("meta", "Details"), plain("lastDate", "Last date"), { name: "url", label: "Upload notice document / file", type: "media", localized: false }],
  },
  {
    id: "tenders",
    label: "Tenders",
    description: "Tender notices and closing dates.",
    fields: [text("title", "Tender title", { required: true }), text("category", "Category"), textarea("meta", "Details"), plain("lastDate", "Closing date"), { name: "url", label: "Upload tender document / file", type: "media", localized: false }],
  },
  {
    id: "faq",
    label: "FAQ",
    description: "Frequently asked questions.",
    fields: [text("title", "Question", { required: true }), textarea("answer", "Answer", { required: true })],
  },
  {
    id: "gallery",
    label: "Gallery",
    description: "Public photographs, captions and accessible alt text. Edit the gallery page title and subheading in Page Headings and Subheadings.",
    fields: [text("title", "Caption"), text("altText", "Alt text", { required: true }), { name: "image", label: "Image", type: "media", localized: false }],
  },
  {
    id: "downloads",
    label: "Downloads",
    description: "Files published specifically on /downloads. Division, notice and flood-report files stay in their owning editors.",
    fields: [text("title", "Title", { required: true }), text("category", "Category"), textarea("summary", "Summary"), plain("date", "Date", { type: "date" }), { name: "url", label: "Upload downloadable file", type: "media", localized: false }],
  },
  {
    id: "flood_reports",
    label: "Flood Reports",
    description: "Daily flood reports and coverage.",
    fields: [text("title", "Title", { required: true }), plain("date", "Date", { type: "date" }), text("dateLabel", "Date label"), text("category", "Category"), text("coverage", "Coverage"), textarea("meta", "Details"), { name: "url", label: "Upload flood report / file", type: "media", localized: false }, { name: "archiveOnly", label: "Show only inside its year archive", type: "boolean", localized: false, booleanLabel: "Archive report" }],
  },
  {
    id: "mobile_apps",
    label: "Mobile Apps",
    description: "Application cards, contextual thumbnails and downloads.",
    fields: [
      text("title", "App title", { required: true }),
      textarea("description", "Description"),
      { name: "thumbnail", label: "App thumbnail", type: "media", localized: false },
      plain("url", "Download URL", { type: "url" }),
      plain("cardColor", "Card colour", { advanced: true }),
      plain("cardColor2", "Second card colour", { advanced: true }),
    ],
  },
  {
    id: "public_info",
    label: "Public Service Pages",
    description: "RTI, Feedback, Tenders and FAQ pages shown on the public website.",
    fields: [
      text("title", "Page title", { required: true }),
      plain("slug", "Page URL slug", { required: true, advanced: true }),
      text("eyebrow", "Small heading"),
      textarea("summary", "Page introduction"),
      { name: "sections", label: "Page sections", type: "json", localized: true },
      { name: "links", label: "Related links", type: "json", localized: true },
      plain("sourceUrl", "Source URL", { type: "url", advanced: true }),
      plain("sort", "Legacy order", { type: "number", advanced: true }),
    ],
  },
  {
    id: "policies",
    label: "Website Policies",
    description: "Terms, privacy, copyright, accessibility, disclaimer, help and hyperlinking pages.",
    fields: [
      text("title", "Policy title", { required: true }),
      plain("slug", "Page URL slug", { required: true, advanced: true }),
      textarea("summary", "Policy introduction"),
      { name: "sections", label: "Policy sections", type: "json", localized: true },
      plain("sourceUrl", "Source URL", { type: "url", advanced: true }),
      plain("sort", "Legacy order", { type: "number", advanced: true }),
    ],
  },
  {
    id: "menu_items",
    label: "Header / Footer Menu",
    description: "Navigation items and child links.",
    fields: [text("title", "Menu title", { required: true }), textarea("description", "Description"), plain("path", "Path", { required: true }), { name: "links", label: "Child links", type: "json", localized: true }],
  },
  {
    id: "contact",
    label: "Contact",
    description: "Address, email, phone and contact rows.",
    singleton: true,
    fields: [text("title", "Title"), textarea("address", "Address"), plain("email", "Email", { type: "email" }), plain("phone", "Phone"), plain("mobile", "Mobile"), { name: "contacts", label: "Contact rows", type: "json", localized: true }],
  },
  {
    id: "site_settings",
    label: "Homepage, Sitemap and Global Text",
    description: "Homepage sections, sitemap headings and links, gallery, location, footer and other shared website text in friendly groups.",
    singleton: true,
    fields: [{ name: "settings", label: "Website settings", type: "json", localized: true, required: true }],
  },
  {
    id: "page_display_settings",
    label: "Page Headings and Subheadings",
    description: "Rename, resize, hide, or adjust any route, and add optional text, photos, galleries, cards, tables or downloads before or after its existing content.",
    fields: [
      plain("path", "Page path", { required: true }),
      text("eyebrow", "Small heading / flag text"),
      text("title", "Main page heading override (blank keeps current heading)"),
      textarea("intro", "Subheading / page introduction"),
      { name: "hideEyebrow", label: "Hide small heading", type: "boolean", localized: false, booleanLabel: "Hidden" },
      { name: "hideTitle", label: "Hide main heading", type: "boolean", localized: false, booleanLabel: "Hidden" },
      { name: "hideIntro", label: "Hide subheading / introduction", type: "boolean", localized: false, booleanLabel: "Hidden" },
      { name: "eyebrowSize", label: "Small heading / flag size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }] },
      { name: "headingSize", label: "Heading size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }] },
      { name: "contentSize", label: "Body text size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }] },
      { name: "contentWidth", label: "Content width", type: "select", localized: false, options: [{ value: "compact", label: "Narrow" }, { value: "normal", label: "Normal" }, { value: "wide", label: "Wide" }, { value: "full", label: "Full width" }] },
      { name: "mediaSize", label: "Content image size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }, { value: "full", label: "Full width" }] },
      { name: "contentSpacing", label: "Content spacing", type: "select", localized: false, options: [{ value: "compact", label: "Compact" }, { value: "normal", label: "Normal" }, { value: "relaxed", label: "Relaxed" }] },
      { name: "beforeBlocks", label: "Extra sections before the current page content", type: "blocks", localized: true },
      { name: "afterBlocks", label: "Extra sections after the current page content", type: "blocks", localized: true },
    ],
  },
  {
    id: "design_settings",
    label: "Website Design and Fonts",
    description: "Change the complete website font, base text size, spacing, backgrounds and card appearance.",
    singleton: true,
    fields: [
      { name: "siteFont", label: "Complete website font", type: "select", localized: false, defaultValue: "Inter", options: [{ value: "Inter", label: "Inter - Clean and modern" }, { value: "Plus Jakarta Sans", label: "Plus Jakarta Sans - Friendly and modern" }, { value: "System Sans", label: "System Sans - Simple" }, { value: "System Serif", label: "System Serif - Traditional" }] },
      { name: "bodyFont", label: "Advanced body font override", type: "select", localized: false, advanced: true, options: ["Inter", "Plus Jakarta Sans", "System Sans", "System Serif"] },
      { name: "headingFont", label: "Advanced heading font override", type: "select", localized: false, advanced: true, options: ["Plus Jakarta Sans", "Inter", "System Sans", "System Serif"] },
      { name: "hindiFont", label: "Advanced Hindi font override", type: "select", localized: false, advanced: true, options: ["Noto Sans Devanagari", "System Devanagari"] },
      { name: "baseFontSize", label: "Base font size (14-20 px)", type: "number", localized: false },
      { name: "surfaceStyle", label: "Page background style", type: "select", localized: false, defaultValue: "atlas", options: [{ value: "atlas", label: "Civic atlas grid" }, { value: "clean", label: "Clean white" }, { value: "bands", label: "Soft section bands" }] },
      { name: "contentDensity", label: "Page spacing", type: "select", localized: false, defaultValue: "comfortable", options: [{ value: "compact", label: "Compact" }, { value: "comfortable", label: "Comfortable" }, { value: "spacious", label: "Spacious" }] },
      { name: "cornerStyle", label: "Card corners", type: "select", localized: false, defaultValue: "precise", options: [{ value: "precise", label: "Precise (8 px)" }, { value: "soft", label: "Soft (12 px)" }] },
      { name: "cardElevation", label: "Card depth", type: "select", localized: false, defaultValue: "quiet", options: [{ value: "quiet", label: "Quiet" }, { value: "lifted", label: "Lifted" }] },
      { name: "motionLevel", label: "Interface motion", type: "select", localized: false, defaultValue: "standard", options: [{ value: "none", label: "None" }, { value: "reduced", label: "Reduced" }, { value: "standard", label: "Standard" }] },
    ],
  },
  {
    id: "hero_banners",
    label: "Hero Banners / Videos",
    description: "Homepage hero media and titles.",
    fields: [text("title", "Title", { required: true }), plain("fileName", "File name"), { name: "video", label: "Video", type: "media", localized: false }, { name: "videoLarge", label: "Large-screen video (optional)", type: "media", localized: false }, { name: "poster", label: "Poster image", type: "media", localized: false }, { name: "active", label: "Active", type: "boolean", localized: false }],
  },
  {
    id: "logos",
    label: "Header / Footer Logos",
    description: "RSAC and government logos.",
    fields: [text("title", "Logo title", { required: true }), text("altText", "Alt text", { required: true }), { name: "image", label: "Logo image", type: "media", localized: false }, plain("linkUrl", "Link URL", { type: "url" }), { name: "placement", label: "Placement", type: "select", localized: false, options: ["primary", "supporting", "footer"] }],
  },
  ...[
    ["homepage_features", "Homepage Feature Tabs", "Objective, implementation, approach and activity tabs."],
    ["services", "Services / Programme Cards", "Homepage services and programme cards."],
    ["applications", "Application Cards", "Homepage application cards."],
    ["quick_links", "Quick Links", "Homepage quick links."],
    ["geoportals", "Geoportals", "Geoportal cards and URLs."],
  ].map(([id, label, description]) => ({
    id,
    label,
    description,
    fields: [
      text("title", "Title", { required: true }),
      textarea("description", "Description"),
      textarea("details", "Details"),
      plain("path", "Path"),
      plain("url", "URL", { type: "url" }),
      { name: "iconKey", label: "Icon", type: "select", localized: false, options: cmsIconOptions },
      text("category", "Category"),
      {
        name: "buttonLabel",
        label: "Button label",
        type: "suggestions",
        localized: true,
        options: cmsButtonLabelSuggestions,
        hidden: id === "homepage_features",
      },
      ...(id === "quick_links" ? [{ name: "accent", label: "Card accent colour", type: "color", localized: false }] : []),
      ...(id === "geoportals" ? [
        plain("accent", "Accent style", { advanced: true }),
        { name: "accentHex", label: "Icon accent colour", type: "color", localized: false },
      ] : []),
    ],
  })),
  {
    id: "operational_domains",
    label: "Operational Domains",
    description: "Cards around homepage operational-domain sphere.",
    fields: [text("label", "Label", { required: true }), text("detail", "Detail"), text("tagline", "Tagline"), { name: "deliverables", label: "Deliverables", type: "list", localized: true }, plain("path", "Path"), { name: "icon", label: "Icon", type: "select", localized: false, options: cmsIconOptions }, text("statValue", "Statistic value"), text("statLabel", "Statistic label"), { name: "linkLabel", label: "Link label", type: "suggestions", localized: true, options: cmsButtonLabelSuggestions }],
  },
  {
    id: "impact_stats",
    label: "Impact Statistics",
    description: "Homepage institutional statistics.",
    fields: [text("label", "Label", { required: true }), text("value", "Value", { required: true }), textarea("detail", "Detail")],
  },
  {
    id: "manpower",
    label: "Manpower Groups",
    description: "Manpower summary cards.",
    fields: [text("title", "Title", { required: true }), text("count", "Count"), textarea("text", "Description"), plain("path", "Path")],
  },
  {
    id: "organisation_roles",
    label: "Organisation Chart",
    description: "Organisation chart roles and photographs.",
    fields: [text("title", "Group title"), plain("roleKey", "Role key", { required: true }), plain("groupKey", "Group key"), plain("slot", "Slot"), text("name", "Name", { required: true }), text("role", "Role"), text("post", "Post"), { name: "photo", label: "Photo", type: "media", localized: false }, plain("objectPosition", "Photo position")],
  },
];

export const collectionMap = new Map(collections.map((collection) => [collection.id, collection]));

export const getCollection = (id) => collectionMap.get(id) || null;
