const text = (name, label, options = {}) => ({ name, label, type: "text", localized: true, ...options });
const textarea = (name, label, options = {}) => ({ name, label, type: "textarea", localized: true, ...options });
const plain = (name, label, options = {}) => ({ name, label, type: "text", localized: false, ...options });

const divisionOptions = [
  ["agriculture-resources-division1", "Agriculture Resources Division"],
  ["computer-image-processing-division", "Computer Image Processing & Data Management"],
  ["earth-resources-division1", "Earth Resources Division"],
  ["forest-resources-ecology-division", "Forest Resources and Ecology Division"],
  ["groundwater-resources-division1", "Groundwater Resources Division"],
  ["geo-spatial-data-bank-division1", "Geo-Spatial Data Bank Division"],
  ["landuse-amp;-urban-survey-division1", "Landuse and Urban Survey Division"],
  ["soil-resources-division1", "Soil Resources Division"],
  ["surface-water-resources-division1", "Surface Water Resources Division"],
  ["training-division", "Training Division"],
  ["school-of-geo-informatics-division1", "School of Geo-Informatics"],
].map(([value, label]) => ({ value, label }));

const divisionSectionOptions = [
  ["ongoing-projects", "Ongoing Projects"],
  ["completed-projects", "Completed Projects"],
  ["research-papers", "Research Papers / List of Research Papers"],
  ["technical-reports", "Technical Reports"],
  ["publications", "Publications"],
  ["training-programmes", "Training Programmes"],
  ["training-hostel", "Training Hostel"],
  ["overview", "Division Overview / Other List"],
].map(([value, label]) => ({ value, label }));

export const blockTypes = [
  { value: "hero", label: "Hero banner" },
  { value: "rich_text", label: "Text / paragraph" },
  { value: "cards", label: "Responsive cards" },
  { value: "image", label: "Image" },
  { value: "gallery", label: "Gallery" },
  { value: "stats", label: "Statistics" },
  { value: "links", label: "Links / downloads" },
  { value: "table", label: "Table" },
  { value: "callout", label: "Notice / callout" },
  { value: "divider", label: "Divider line" },
];

export const collections = [
  {
    id: "pages",
    label: "All Website Pages",
    description: "About, division, facility, policy, service, programme and public-information pages.",
    fields: [
      text("title", "Page title", { required: true }),
      plain("slug", "URL slug", { required: true, advanced: true }),
      plain("sectionKey", "Section key", { required: true, advanced: true }),
      text("eyebrow", "Eyebrow"),
      textarea("summary", "Summary"),
      { name: "html", label: "Legacy imported page content", type: "richtext", localized: true, advanced: true },
      { name: "blocks", label: "Flexible page blocks", type: "blocks", localized: true },
      { name: "featuredImage", label: "Featured image", type: "media", localized: false },
      { name: "headingSize", label: "Page heading size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }] },
      { name: "contentSize", label: "Body text size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }] },
      { name: "contentWidth", label: "Content width", type: "select", localized: false, options: [{ value: "compact", label: "Narrow" }, { value: "normal", label: "Normal" }, { value: "wide", label: "Wide" }, { value: "full", label: "Full width" }] },
      { name: "mediaSize", label: "Content image size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }, { value: "full", label: "Full width" }] },
      { name: "contentSpacing", label: "Content spacing", type: "select", localized: false, options: [{ value: "compact", label: "Compact" }, { value: "normal", label: "Normal" }, { value: "relaxed", label: "Relaxed" }] },
      plain("sourceUrl", "Source URL", { type: "url", advanced: true }),
      plain("cardIcon", "Card icon", { advanced: true }),
      plain("cardColor", "Card colour", { advanced: true }),
      plain("cardColor2", "Second card colour", { advanced: true }),
    ],
  },
  {
    id: "page_sections",
    label: "Page Groups",
    description: "Top-level route groups and section introductions.",
    fields: [text("title", "Title", { required: true }), plain("key", "Key", { required: true }), plain("route", "Route"), text("eyebrow", "Eyebrow"), textarea("intro", "Introduction")],
  },
  {
    id: "divisions",
    label: "Divisions",
    description: "Division cards and summaries.",
    fields: [text("title", "Division name", { required: true }), plain("slug", "Slug", { required: true }), textarea("lead", "Lead"), { name: "highlights", label: "Highlights", type: "list", localized: true }, plain("sourceUrl", "Source URL", { type: "url" })],
  },
  {
    id: "division_section_items",
    label: "Division List Items",
    description: "Add research papers, completed or ongoing projects, reports, publications and other division list records using a simple form.",
    autoNewestFirst: true,
    requireHindiWhenPublished: true,
    fields: [
      { name: "divisionSlug", label: "Division", type: "select", localized: false, required: true, options: divisionOptions },
      { name: "sectionKey", label: "Website section", type: "select", localized: false, required: true, options: divisionSectionOptions },
      text("title", "Item title", { required: true }),
      text("authors", "Authors / responsible officers"),
      text("publicationName", "Journal / department / publisher"),
      textarea("details", "Description / citation / project details"),
      plain("year", "Year", { type: "number" }),
      plain("date", "Date", { type: "date" }),
      { name: "documentUrl", label: "Upload document / file", type: "media", localized: false },
      plain("externalUrl", "External webpage URL", { type: "url" }),
    ],
  },
  {
    id: "facilities",
    label: "Facility Ordering Data",
    description: "Internal facility-card ordering data. Editors normally use the Facilities page collection.",
    fields: [text("title", "Facility name", { required: true }), plain("slug", "Slug", { required: true }), textarea("text", "Description")],
  },
  {
    id: "profiles",
    label: "Scientists / Officials / Staff",
    description: "Scientists, leadership, officials, former staff, technical staff and administration.",
    fields: [
      text("name", "Name", { required: true }),
      { name: "profileType", label: "Profile type", type: "select", localized: false, options: ["scientist", "official", "leadership", "former", "technical", "administration"] },
      text("role", "Role"), text("designation", "Designation"), text("department", "Department"), text("deployment", "Deployment"), plain("employeeId", "Employee ID"), text("duration", "Duration"),
      { name: "photo", label: "Photo", type: "media", localized: false }, plain("objectPosition", "Photo position"), textarea("specialization", "Specialization"), text("experience", "Experience"), text("publications", "Publications"), plain("contact", "Contact"), plain("email", "Email", { type: "email" }), plain("sourceUrl", "Source URL", { type: "url" }), text("category", "Category"), { name: "details", label: "Details", type: "list", localized: true },
    ],
  },
  {
    id: "projects",
    label: "Projects",
    description: "Completed and ongoing projects.",
    fields: [text("title", "Project title", { required: true }), { name: "type", label: "Project type", type: "select", localized: false, options: ["ongoing", "completed"] }, plain("divisionSlug", "Division slug"), plain("year", "Year"), text("client", "Client"), textarea("summary", "Summary"), plain("url", "Project document", { type: "url" })],
  },
  {
    id: "publications",
    label: "Publications / Research / Reports",
    description: "Research papers, technical reports, atlases and plans.",
    fields: [text("title", "Title", { required: true }), { name: "type", label: "Type", type: "select", localized: false, options: ["publication", "research_paper", "technical_report", "atlas", "plan"] }, plain("divisionSlug", "Division slug"), plain("year", "Year"), textarea("authors", "Authors"), textarea("citation", "Citation"), textarea("summary", "Summary"), plain("url", "Document URL", { type: "url" })],
  },
  {
    id: "notices",
    label: "Notices",
    description: "Public notices and documents.",
    fields: [text("title", "Notice title", { required: true }), text("category", "Category"), textarea("meta", "Details"), plain("lastDate", "Last date"), plain("url", "Document URL", { type: "url" })],
  },
  {
    id: "tenders",
    label: "Tenders",
    description: "Tender notices and closing dates.",
    fields: [text("title", "Tender title", { required: true }), text("category", "Category"), textarea("meta", "Details"), plain("lastDate", "Closing date"), plain("url", "Document URL", { type: "url" })],
  },
  {
    id: "faq",
    label: "FAQ",
    description: "Frequently asked questions.",
    fields: [text("title", "Question", { required: true }), textarea("answer", "Answer", { required: true })],
  },
  {
    id: "gallery",
    label: "Gallery",
    description: "Public photographs, captions and accessible alt text.",
    fields: [text("title", "Caption", { required: true }), text("altText", "Alt text", { required: true }), { name: "image", label: "Image", type: "media", localized: false }],
  },
  {
    id: "downloads",
    label: "Downloads",
    description: "Public documents and files.",
    fields: [text("title", "Title", { required: true }), text("category", "Category"), textarea("summary", "Summary"), plain("date", "Date"), plain("url", "File URL", { type: "url" })],
  },
  {
    id: "flood_reports",
    label: "Flood Reports",
    description: "Daily flood reports and coverage.",
    fields: [text("title", "Title", { required: true }), plain("date", "Date"), text("dateLabel", "Date label"), text("category", "Category"), text("coverage", "Coverage"), textarea("meta", "Details"), plain("url", "Document URL", { type: "url" })],
  },
  {
    id: "mobile_apps",
    label: "Mobile Apps",
    description: "Application cards, contextual thumbnails and downloads.",
    fields: [
      text("title", "App title", { required: true }),
      textarea("description", "Description"),
      { name: "thumbnail", label: "App thumbnail", type: "media", localized: false },
      plain("url", "Download URL", { type: "url" }),
      plain("cardColor", "Card colour", { advanced: true }),
      plain("cardColor2", "Second card colour", { advanced: true }),
    ],
  },
  {
    id: "public_info",
    label: "Public Service Pages",
    description: "RTI, Feedback, Tenders and FAQ pages shown on the public website.",
    fields: [
      text("title", "Page title", { required: true }),
      plain("slug", "Page URL slug", { required: true, advanced: true }),
      text("eyebrow", "Small heading"),
      textarea("summary", "Page introduction"),
      { name: "sections", label: "Page sections", type: "json", localized: true },
      { name: "links", label: "Related links", type: "json", localized: true },
      plain("sourceUrl", "Source URL", { type: "url", advanced: true }),
      plain("sort", "Legacy order", { type: "number", advanced: true }),
    ],
  },
  {
    id: "policies",
    label: "Website Policies",
    description: "Terms, privacy, copyright, accessibility, disclaimer, help and hyperlinking pages.",
    fields: [
      text("title", "Policy title", { required: true }),
      plain("slug", "Page URL slug", { required: true, advanced: true }),
      textarea("summary", "Policy introduction"),
      { name: "sections", label: "Policy sections", type: "json", localized: true },
      plain("sourceUrl", "Source URL", { type: "url", advanced: true }),
      plain("sort", "Legacy order", { type: "number", advanced: true }),
    ],
  },
  {
    id: "menu_items",
    label: "Header / Footer Menu",
    description: "Navigation items and child links.",
    fields: [text("title", "Menu title", { required: true }), textarea("description", "Description"), plain("path", "Path", { required: true }), { name: "links", label: "Child links", type: "json", localized: true }],
  },
  {
    id: "contact",
    label: "Contact",
    description: "Address, email, phone and contact rows.",
    singleton: true,
    fields: [text("title", "Title"), textarea("address", "Address"), plain("email", "Email", { type: "email" }), plain("phone", "Phone"), plain("mobile", "Mobile"), { name: "contacts", label: "Contact rows", type: "json", localized: true }],
  },
  {
    id: "site_settings",
    label: "Homepage and Global Text",
    description: "Homepage section visibility, hero, About, services, statistics, location, gallery and footer text in friendly groups.",
    singleton: true,
    fields: [{ name: "settings", label: "Website settings", type: "json", localized: true, required: true }],
  },
  {
    id: "page_display_settings",
    label: "Page Headings",
    description: "Rename, resize, hide, or adjust the content layout for any website route.",
    fields: [
      plain("path", "Page path", { required: true }),
      text("eyebrow", "Small heading / flag text"),
      text("title", "Main page heading override (blank keeps current heading)"),
      textarea("intro", "Page introduction"),
      { name: "hideEyebrow", label: "Hide small heading", type: "boolean", localized: false, booleanLabel: "Hidden" },
      { name: "hideTitle", label: "Hide main heading", type: "boolean", localized: false, booleanLabel: "Hidden" },
      { name: "hideIntro", label: "Hide introduction", type: "boolean", localized: false, booleanLabel: "Hidden" },
      { name: "headingSize", label: "Heading size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }] },
      { name: "contentSize", label: "Body text size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }] },
      { name: "contentWidth", label: "Content width", type: "select", localized: false, options: [{ value: "compact", label: "Narrow" }, { value: "normal", label: "Normal" }, { value: "wide", label: "Wide" }, { value: "full", label: "Full width" }] },
      { name: "mediaSize", label: "Content image size", type: "select", localized: false, options: [{ value: "compact", label: "Small" }, { value: "normal", label: "Normal" }, { value: "large", label: "Large" }, { value: "full", label: "Full width" }] },
      { name: "contentSpacing", label: "Content spacing", type: "select", localized: false, options: [{ value: "compact", label: "Compact" }, { value: "normal", label: "Normal" }, { value: "relaxed", label: "Relaxed" }] },
    ],
  },
  {
    id: "design_settings",
    label: "Design Settings",
    description: "Safe global typography controls. Values are constrained to bundled government-friendly fonts and responsive sizes.",
    singleton: true,
    fields: [
      { name: "bodyFont", label: "English body font", type: "select", localized: false, options: ["Inter", "Plus Jakarta Sans", "System Sans", "System Serif"] },
      { name: "headingFont", label: "English heading font", type: "select", localized: false, options: ["Plus Jakarta Sans", "Inter", "System Sans", "System Serif"] },
      { name: "hindiFont", label: "Hindi font", type: "select", localized: false, options: ["Noto Sans Devanagari", "System Devanagari"] },
      { name: "baseFontSize", label: "Base font size (14-20 px)", type: "number", localized: false },
    ],
  },
  {
    id: "hero_banners",
    label: "Hero Banners / Videos",
    description: "Homepage hero media and titles.",
    fields: [text("title", "Title", { required: true }), plain("fileName", "File name"), { name: "video", label: "Video", type: "media", localized: false }, { name: "poster", label: "Poster image", type: "media", localized: false }, { name: "active", label: "Active", type: "boolean", localized: false }],
  },
  {
    id: "logos",
    label: "Header / Footer Logos",
    description: "RSAC and government logos.",
    fields: [text("title", "Logo title", { required: true }), text("altText", "Alt text", { required: true }), { name: "image", label: "Logo image", type: "media", localized: false }, plain("linkUrl", "Link URL", { type: "url" }), { name: "placement", label: "Placement", type: "select", localized: false, options: ["primary", "supporting", "footer"] }],
  },
  ...[
    ["homepage_features", "Homepage Feature Tabs", "Objective, implementation, approach and activity tabs."],
    ["services", "Services / Programme Cards", "Homepage services and programme cards."],
    ["applications", "Application Cards", "Homepage application cards."],
    ["quick_links", "Quick Links", "Homepage quick links."],
    ["geoportals", "Geoportals", "Geoportal cards and URLs."],
  ].map(([id, label, description]) => ({
    id,
    label,
    description,
    fields: [text("title", "Title", { required: true }), textarea("description", "Description"), textarea("details", "Details"), plain("path", "Path"), plain("url", "URL", { type: "url" }), plain("iconKey", "Icon"), text("category", "Category"), text("buttonLabel", "Button label")],
  })),
  {
    id: "operational_domains",
    label: "Operational Domains",
    description: "Cards around homepage operational-domain sphere.",
    fields: [text("label", "Label", { required: true }), text("detail", "Detail"), text("tagline", "Tagline"), { name: "deliverables", label: "Deliverables", type: "list", localized: true }, plain("path", "Path"), plain("icon", "Icon"), text("statValue", "Statistic value"), text("statLabel", "Statistic label"), text("linkLabel", "Link label")],
  },
  {
    id: "impact_stats",
    label: "Impact Statistics",
    description: "Homepage institutional statistics.",
    fields: [text("label", "Label", { required: true }), text("value", "Value", { required: true }), textarea("detail", "Detail")],
  },
  {
    id: "manpower",
    label: "Manpower Groups",
    description: "Manpower summary cards.",
    fields: [text("title", "Title", { required: true }), text("count", "Count"), textarea("text", "Description"), plain("path", "Path")],
  },
  {
    id: "organisation_roles",
    label: "Organisation Chart",
    description: "Organisation chart roles and photographs.",
    fields: [text("title", "Group title"), plain("roleKey", "Role key", { required: true }), plain("groupKey", "Group key"), plain("slot", "Slot"), text("name", "Name", { required: true }), text("role", "Role"), text("post", "Post"), { name: "photo", label: "Photo", type: "media", localized: false }, plain("objectPosition", "Photo position")],
  },
];

export const collectionMap = new Map(collections.map((collection) => [collection.id, collection]));

export const getCollection = (id) => collectionMap.get(id) || null;
