// Mirror legacy RSAC-hosted assets into public/official-media and generate the
// URL manifest used by live Directus content. Re-runnable: existing files are
// kept and only missing assets are downloaded.
import {
  access,
  mkdir,
  readFile,
  readdir,
  writeFile,
} from "node:fs/promises";
import { constants } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  findOfficialMediaUrls,
  getOfficialMediaLocalPath,
  normalizeOfficialMediaUrl,
  officialMediaManifest as previousManifest,
} from "../src/data/officialMedia.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const publicDir = path.join(root, "public");
const SOURCE_EXTENSIONS = new Set([".js", ".jsx", ".json"]);
const MANIFEST_FILE = "src/data/officialMediaManifest.generated.js";
const DOWNLOAD_TIMEOUT_MS = 25000;
const DIRECTUS_COLLECTIONS = [
  "rsac_divisions",
  "rsac_facilities",
  "rsac_profiles",
  "rsac_notices",
  "rsac_flood_reports",
  "rsac_policies",
  "rsac_public_info",
  "rsac_pages",
  "rsac_site_settings",
  "rsac_hero_videos",
];

const exists = async (file) => {
  try {
    await access(file, constants.F_OK);
    return true;
  } catch {
    return false;
  }
};

const collectSourceFiles = async (directory) => {
  const files = [];

  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const absolute = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await collectSourceFiles(absolute)));
      continue;
    }

    const relative = path.relative(root, absolute).replaceAll("\\", "/");
    if (
      SOURCE_EXTENSIONS.has(path.extname(entry.name)) &&
      relative !== MANIFEST_FILE
    ) {
      files.push(absolute);
    }
  }

  return files;
};

const collectDirectusUrls = async (urls) => {
  const baseUrl = String(
    process.env.DIRECTUS_URL ||
      process.env.VITE_CMS_URL ||
      "http://localhost:8055"
  ).replace(/\/+$/, "");
  let collectionsRead = 0;

  for (const collection of DIRECTUS_COLLECTIONS) {
    try {
      const response = await fetch(`${baseUrl}/items/${collection}?limit=-1`, {
        signal: AbortSignal.timeout(5000),
      });
      if (!response.ok) continue;

      const body = await response.text();
      findOfficialMediaUrls(body).forEach((url) => urls.add(url));
      collectionsRead++;
    } catch {
      // CMS may be offline when this maintenance script is run.
    }
  }

  return collectionsRead;
};

const writeManifest = async (manifest) => {
  const sorted = Object.fromEntries(
    Object.entries(manifest).sort(([left], [right]) =>
      left.localeCompare(right)
    )
  );
  const contents =
    "// Generated by scripts/localize-media.mjs. Do not edit by hand.\n" +
    `export const officialMediaManifest = ${JSON.stringify(sorted, null, 2)};\n`;

  await writeFile(path.join(root, MANIFEST_FILE), contents, "utf8");
};

const main = async () => {
  const urls = new Set();
  const fileText = new Map();
  const sourceFiles = await collectSourceFiles(path.join(root, "src"));

  for (const absolute of sourceFiles) {
    const relative = path.relative(root, absolute).replaceAll("\\", "/");
    const contents = await readFile(absolute, "utf8");
    fileText.set(relative, contents);
    findOfficialMediaUrls(contents).forEach((url) => urls.add(url));
  }

  const cmsCollectionsRead = await collectDirectusUrls(urls);
  console.log(
    `Found ${urls.size} distinct assets across ${fileText.size} source files` +
      ` and ${cmsCollectionsRead} Directus collections.`
  );

  const manifest = {};
  for (const [url, localPath] of Object.entries(previousManifest)) {
    const existingFile = path.join(publicDir, localPath.replace(/^\/+/, ""));
    if (await exists(existingFile)) {
      manifest[url] = localPath;
    }
  }

  const list = [...urls];
  let ok = 0;
  let fail = 0;
  const concurrency = 8;

  const download = async (url) => {
    const localPath = getOfficialMediaLocalPath(url);
    const normalizedUrl = normalizeOfficialMediaUrl(url);

    if (!localPath) {
      fail++;
      return;
    }

    const destination = path.join(publicDir, localPath.replace(/^\/+/, ""));
    if (await exists(destination)) {
      manifest[normalizedUrl] = localPath;
      ok++;
      return;
    }

    try {
      const response = await fetch(url, {
        redirect: "follow",
        signal: AbortSignal.timeout(DOWNLOAD_TIMEOUT_MS),
      });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);

      const buffer = Buffer.from(await response.arrayBuffer());
      if (!buffer.length) throw new Error("empty response");

      await mkdir(path.dirname(destination), { recursive: true });
      await writeFile(destination, buffer);
      manifest[normalizedUrl] = localPath;
      ok++;
    } catch (error) {
      fail++;
      console.warn(`  FAIL ${url} -> ${error.message}`);
    }
  };

  for (let index = 0; index < list.length; index += concurrency) {
    await Promise.all(list.slice(index, index + concurrency).map(download));
    process.stdout.write(`\r  localized ${ok}/${list.length} (fail ${fail})`);
  }
  process.stdout.write("\n");

  for (const [relative, contents] of fileText) {
    let updated = contents;
    let changed = 0;

    for (const url of urls) {
      const localPath = manifest[normalizeOfficialMediaUrl(url)];
      if (localPath && updated.includes(url)) {
        updated = updated.split(url).join(localPath);
        changed++;
      }
    }

    if (changed) {
      await writeFile(path.join(root, relative), updated, "utf8");
      console.log(`  rewrote ${relative} (${changed} urls)`);
    }
  }

  await writeManifest(manifest);
  console.log(
    `Done. ok=${ok} fail=${fail}, assets hosted under public/official-media.`
  );
};

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
