import {
  Accessibility,
  Activity,
  Award,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  BedDouble,
  Bird,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  ClipboardCheck,
  Compass,
  ContactRound,
  Cpu,
  Database,
  Droplets,
  FileText,
  FlaskConical,
  Globe2,
  GraduationCap,
  Handshake,
  HelpCircle,
  History,
  Home,
  IdCard,
  Images,
  Landmark,
  LandPlot,
  Layers3,
  LibraryBig,
  Map,
  MapPinned,
  MessageCircle,
  Microscope,
  Mountain,
  Network,
  Orbit,
  Printer,
  Radar,
  RadioTower,
  Route,
  Ruler,
  Satellite,
  Scale,
  School,
  ScanLine,
  ScanSearch,
  ScrollText,
  Search,
  Share2,
  ShieldCheck,
  ShieldUser,
  Smartphone,
  Sprout,
  Trees,
  UserCog,
  UserRound,
  UserRoundCheck,
  UsersRound,
  UserStar,
  Waves,
  Waypoints,
  Wrench,
} from "lucide-react";

export const cmsIconMap = {
  accessibility: Accessibility,
  activity: Activity,
  award: Award,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "badge-check": BadgeCheck,
  "bed-double": BedDouble,
  bird: Bird,
  "book-open": BookOpen,
  "briefcase-business": BriefcaseBusiness,
  building: Building2,
  building2: Building2,
  clipboard: ClipboardCheck,
  compass: Compass,
  "contact-round": ContactRound,
  cpu: Cpu,
  database: Database,
  document: FileText,
  droplets: Droplets,
  education: GraduationCap,
  facebook: Share2,
  "file-text": FileText,
  "flask-conical": FlaskConical,
  flood: Waves,
  globe: Globe2,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  help: HelpCircle,
  history: History,
  home: Home,
  "id-card": IdCard,
  images: Images,
  landmark: Landmark,
  "land-plot": LandPlot,
  layers: Layers3,
  "library-big": LibraryBig,
  map: Map,
  "map-pinned": MapPinned,
  microscope: Microscope,
  mountain: Mountain,
  network: Network,
  notices: ScrollText,
  orbit: Orbit,
  phone: Smartphone,
  printer: Printer,
  radar: Radar,
  radio: RadioTower,
  route: Route,
  ruler: Ruler,
  satellite: Satellite,
  scale: Scale,
  school: School,
  scan: ScanLine,
  "scan-line": ScanLine,
  "scan-search": ScanSearch,
  search: Search,
  shield: ShieldCheck,
  "shield-user": ShieldUser,
  sprout: Sprout,
  trees: Trees,
  twitter: MessageCircle,
  "user-cog": UserCog,
  "user-round": UserRound,
  "user-round-check": UserRoundCheck,
  "users-round": UsersRound,
  "user-star": UserStar,
  waves: Waves,
  waypoints: Waypoints,
  wrench: Wrench,
};

export const resolveCmsIcon = (value, fallback = FileText) =>
  cmsIconMap[String(value || "").trim().toLowerCase()] || fallback;
