import {
  Accessibility,
  Activity,
  ArrowRight,
  ArrowUpRight,
  BedDouble,
  Bird,
  BookOpen,
  Building2,
  ClipboardCheck,
  Compass,
  Cpu,
  Database,
  Droplets,
  FileText,
  FlaskConical,
  Globe2,
  GraduationCap,
  HelpCircle,
  Home,
  Images,
  Landmark,
  Layers3,
  Map,
  MessageCircle,
  Mountain,
  Network,
  Orbit,
  Printer,
  Radar,
  RadioTower,
  Route,
  Ruler,
  Satellite,
  ScanLine,
  ScrollText,
  Search,
  Share2,
  ShieldCheck,
  Smartphone,
  Sprout,
  Trees,
  UserRound,
  Waves,
  Wrench,
} from "lucide-react";

export const cmsIconMap = {
  accessibility: Accessibility,
  activity: Activity,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "bed-double": BedDouble,
  bird: Bird,
  "book-open": BookOpen,
  building: Building2,
  building2: Building2,
  clipboard: ClipboardCheck,
  compass: Compass,
  cpu: Cpu,
  database: Database,
  document: FileText,
  droplets: Droplets,
  education: GraduationCap,
  facebook: Share2,
  "file-text": FileText,
  "flask-conical": FlaskConical,
  flood: Waves,
  globe: Globe2,
  "graduation-cap": GraduationCap,
  help: HelpCircle,
  home: Home,
  images: Images,
  landmark: Landmark,
  layers: Layers3,
  map: Map,
  mountain: Mountain,
  network: Network,
  notices: ScrollText,
  orbit: Orbit,
  phone: Smartphone,
  printer: Printer,
  radar: Radar,
  radio: RadioTower,
  route: Route,
  ruler: Ruler,
  satellite: Satellite,
  scan: ScanLine,
  "scan-line": ScanLine,
  search: Search,
  shield: ShieldCheck,
  sprout: Sprout,
  trees: Trees,
  twitter: MessageCircle,
  "user-round": UserRound,
  waves: Waves,
  wrench: Wrench,
};

export const resolveCmsIcon = (value, fallback = FileText) =>
  cmsIconMap[String(value || "").trim().toLowerCase()] || fallback;
